name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/mrjayoc -Dtoken=15e4b67c6041d6dec670c886b807be524dfce3ba
      run: mvn -B package --file pom.xml
    
